services:

  imposting-app:
    container_name: imposting-app
    build: .
    command: uv run waitress-serve --threads 6 --listen=*:8000 core.wsgi:application
    restart: unless-stopped
    tty: true
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - web

  imposting-poster:
    container_name: imposting-poster
    build: .
    command: python manage.py runposter
    restart: unless-stopped
    tty: true
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env
    networks:
      - web

networks:
  web:
    external: true
