# Generated by Django 5.2 on 2025-05-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialsched', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='posted',
            new_name='process_image',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='error_facebook',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='error_instagram',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='error_linkedin',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='error_x',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
