# Generated by Django 5.2 on 2025-06-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialsched', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='retries_facebook',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='retries_instagram',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='retries_linkedin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='retries_tiktok',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='retries_x',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
