# Generated by Django 5.2 on 2025-06-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialsched', '0002_rename_posted_postmodel_process_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='error_tiktok',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='link_tiktok',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='post_on_tiktok',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
