# Generated by Django 5.2 on 2025-06-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialsched', '0003_postmodel_error_tiktok_postmodel_link_tiktok_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
                ('comment_disabled', models.BooleanField()),
                ('duet_disabled', models.BooleanField()),
                ('stitch_disabled', models.BooleanField()),
                ('max_video_post_duration_sec', models.IntegerField()),
                ('privacy_level_options', models.CharField(choices=[('FOLLOWER_OF_CREATOR', 'Followers of Creator'), ('PUBLIC_TO_EVERYONE', 'Public to Everyone'), ('MUTUAL_FOLLOW_FRIENDS', 'Mutual Follow Friends'), ('SELF_ONLY', 'Self Only')], max_length=1000)),
            ],
        ),
    ]
