# Generated by Django 5.2 on 2025-06-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_integrationsmodel_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsmodel',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='integrationsmodel',
            name='username',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
